env:
  browser: true
  es6: true
  node: true
extends: airbnb-base
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules: 
  indent: 0
  lines-between-class-members: 0
  padded-blocks: 0
  no-trailing-spaces: 0
  eol-last: 0
  no-unused-vars: 0
